version: "2"
services:

  consul:
    command: -server -bootstrap
    image: gliderlabs/consul-server
    ports:
      - "8300"
      - "8400"
      - "8500:8500"
      - "53"

  nginx:
    image: openlmis/nginx:${OL_NGINX_VERSION}
    ports:
      - "80:80"
    env_file: .manual-api-test-env
    depends_on: [consul]

  reference-ui:
    image: openlmis/reference-ui:${OL_REFERENCE_UI_VERSION}
    env_file: .manual-api-test-env
    depends_on: [consul]

  stockmanagement:
    image: openlmis/stockmanagement:${OL_STOCKMANAGEMENT_VERSION}
    ports:
      - "5005:5005"
      - "8080:8080"
    volumes:
      - '..:/app'
      - 'gradlecache:/gradle'
    env_file: .manual-api-test-env
    depends_on: [log, db,nginx,auth,referencedata,reference-ui,consul,redis]

  auth:
    image: openlmis/auth:${OL_AUTH_VERSION}
    env_file: .manual-api-test-env
    environment:
      JAVA_OPTS: '-Dflyway.locations=classpath:db/migration'
    depends_on: [consul,log,db]

  referencedata:
    image: openlmis/referencedata:${OL_REFERENCEDATA_VERSION}
    env_file: .manual-api-test-env
    environment:
      JAVA_OPTS: '-Dflyway.locations=classpath:db/migration'
    depends_on: [consul,log,db,redis]

  db:
    image: openlmis/postgres:${OL_POSTGRES_VERSION}
    ports:
      - "5432:5432"
    env_file: .manual-api-test-env

  log:
    image: openlmis/rsyslog:1

  redis:
    image: redis:3.2.12
    depends_on: [consul]

volumes:
  gradlecache:
    external: false
